version: '3.9'
services:
  web:
    image: httpd:2.4    #use httpd to serve simple static file
    ports:
      - "4200:80"    #use port 4200 to explore our application
    volumes:
      - ./html:/usr/local/apache2/htdocs
